// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Products.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_products_created_at_utc");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_products_created_by");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_products_updated_by");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.Todos.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date_utc");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_todos_created_by");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_todos_updated_by");

                    b.HasIndex("OwnerUserId", "IsCompleted")
                        .HasDatabaseName("ix_todos_owner_user_id_is_completed");

                    b.ToTable("todos", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_permissions_name");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("34fa5c42-9981-b912-3d92-520d024a934a"),
                            Description = "Create todo",
                            Name = "create:todo"
                        },
                        new
                        {
                            Id = new Guid("8243ef35-3764-a5ad-8d19-c092f7b5eda5"),
                            Description = "Read todo",
                            Name = "read:todo"
                        },
                        new
                        {
                            Id = new Guid("c2251b89-ad44-b870-3970-3b759236b276"),
                            Description = "Update todo",
                            Name = "update:todo"
                        },
                        new
                        {
                            Id = new Guid("78d293f3-e805-fc2c-bc91-53905131b862"),
                            Description = "Delete todo",
                            Name = "delete:todo"
                        },
                        new
                        {
                            Id = new Guid("59476916-57a5-3c4d-c5ff-d4b89ba136b9"),
                            Description = "Create product",
                            Name = "create:product"
                        },
                        new
                        {
                            Id = new Guid("0cd3edf6-686d-d4ae-ff47-b9d3bbbfbe69"),
                            Description = "Read product",
                            Name = "read:product"
                        },
                        new
                        {
                            Id = new Guid("e1903468-a0e4-73f6-86d2-8187c669a819"),
                            Description = "Update product",
                            Name = "update:product"
                        },
                        new
                        {
                            Id = new Guid("575735b2-7b8a-b45f-91f0-e4763fc17672"),
                            Description = "Delete product",
                            Name = "delete:product"
                        },
                        new
                        {
                            Id = new Guid("8c4558ae-4d3e-9b2e-5d92-c66ae44405a7"),
                            Description = "Create user",
                            Name = "create:user"
                        },
                        new
                        {
                            Id = new Guid("c9e8cc75-68f3-82db-6581-9d5a3c104560"),
                            Description = "Read user",
                            Name = "read:user"
                        },
                        new
                        {
                            Id = new Guid("77aeadbe-6e8a-8ed2-82c1-0d78e92801c7"),
                            Description = "Update user",
                            Name = "update:user"
                        },
                        new
                        {
                            Id = new Guid("a27d8f7d-6d6b-ba97-631d-cf6271e6993b"),
                            Description = "Delete user",
                            Name = "delete:user"
                        });
                });

            modelBuilder.Entity("Domain.Users.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Users.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Every permission the API defines.",
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Baseline access: full control over the caller's own todos.",
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_normalized");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_users_created_by");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email_normalized");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_users_updated_by");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("role_id", "permission_id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("permission_id")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("34fa5c42-9981-b912-3d92-520d024a934a")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("8243ef35-3764-a5ad-8d19-c092f7b5eda5")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("c2251b89-ad44-b870-3970-3b759236b276")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("78d293f3-e805-fc2c-bc91-53905131b862")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("59476916-57a5-3c4d-c5ff-d4b89ba136b9")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("0cd3edf6-686d-d4ae-ff47-b9d3bbbfbe69")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("e1903468-a0e4-73f6-86d2-8187c669a819")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("575735b2-7b8a-b45f-91f0-e4763fc17672")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("8c4558ae-4d3e-9b2e-5d92-c66ae44405a7")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("c9e8cc75-68f3-82db-6581-9d5a3c104560")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("77aeadbe-6e8a-8ed2-82c1-0d78e92801c7")
                        },
                        new
                        {
                            role_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            permission_id = new Guid("a27d8f7d-6d6b-ba97-631d-cf6271e6993b")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("34fa5c42-9981-b912-3d92-520d024a934a")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("8243ef35-3764-a5ad-8d19-c092f7b5eda5")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("c2251b89-ad44-b870-3970-3b759236b276")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("78d293f3-e805-fc2c-bc91-53905131b862")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("59476916-57a5-3c4d-c5ff-d4b89ba136b9")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("0cd3edf6-686d-d4ae-ff47-b9d3bbbfbe69")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("e1903468-a0e4-73f6-86d2-8187c669a819")
                        },
                        new
                        {
                            role_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            permission_id = new Guid("575735b2-7b8a-b45f-91f0-e4763fc17672")
                        });
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("user_id", "role_id")
                        .HasName("pk_user_roles");

                    b.HasIndex("role_id")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Products.Entities.Product", b =>
                {
                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_created_by");

                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_updated_by");
                });

            modelBuilder.Entity("Domain.Todos.Entities.Todo", b =>
                {
                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_todos_created_by");

                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todos_owner_user");

                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_todos_updated_by");
                });

            modelBuilder.Entity("Domain.Users.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user");
                });

            modelBuilder.Entity("Domain.Users.Entities.User", b =>
                {
                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_created_by");

                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_updated_by");
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.HasOne("Domain.Users.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permission");

                    b.HasOne("Domain.Users.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role");
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("Domain.Users.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");
                });
#pragma warning restore 612, 618
        }
    }
}
